"""add Department

Revision ID: 22adb0b1df70
Revises: d81dbbd84e43
Create Date: 2024-10-02 14:18:59.174683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22adb0b1df70'
down_revision = 'd81dbbd84e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
